inventario/gestion_inventario/urls.py
# urls.py en tu aplicación gestion_inventario
from django.urls import path # Importamos path
from . import views # Importamos views

urlpatterns = [ # Definimos las rutas
    path('', views.LoginList.as_view(), name='login'), # Ruta para la página de inicio
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'), # Ruta para el dashboard 
    path('registro/', views.RegistroList.as_view(), name='registro'), # Ruta para el registro
    path('login/', views.LoginList.as_view(), name='login'), # Ruta para el login
    path('logout/', views.LogoutList.as_view(), name='logout'), # Ruta para el logout
    path('proveedores/', views.ProveedorList.as_view(), name='proveedor-list'), # Ruta para la lista de proveedores
    path('proveedores/nuevo/', views.ProveedorCreate.as_view(), name='proveedor-create'), # Ruta para crear un nuevo proveedor
    path('proveedores/<int:pk>/editar/', views.ProveedorUpdate.as_view(), name='proveedor-update'), # Ruta para editar un proveedor 
    path('proveedores/<int:pk>/borrar/', views.ProveedorDelete.as_view(), name='proveedor-delete'), # Ruta para borrar un proveedor
    path('productos/', views.ProductoList.as_view(), name='producto-list'), # Ruta para la lista de productos
    path('productos/nuevo/', views.ProductoCreate.as_view(), name='producto-create'), # Ruta para crear un nuevo producto
    path('productos/<int:pk>/editar/', views.ProductoUpdate.as_view(), name='producto-update'), # Ruta para editar un proyecto
    path('productos/<int:pk>/borrar/', views.ProductoDelete.as_view(), name='producto-delete'), # Ruta para borrar un proyecto
    path('pedidos/', views.PedidoList.as_view(), name='pedido-list'), # Ruta para la lista de pedidos
    path('pedidos/nuevo/', views.PedidoCreate.as_view(), name='pedido-create'), # Ruta para crear un nuevo pedido
    path('pedidos/<int:pk>/editar/', views.PedidoUpdate.as_view(), name='pedido-update'), # Ruta para editar un pedido
    path('pedidos/<int:pk>/borrar/', views.PedidoDelete.as_view(), name='pedido-delete'), # Ruta para borrar un pedido
    path('productos/lista/', views.lista_productos, name='lista-productos'), # Ruta para la lista de productos
    path('informes/stock/', views.informe_stock, name='informe-stock'), # Ruta para el informe de stock
    path('grafico_stock/', views.grafico_stock, name='grafico_stock'), # Ruta para el grafico de stock
    path('descargar_grafico_stock/', views.descargar_grafico_stock, name='descargar_grafico_stock'), # Ruta para descargar el grafico de stock
]

inventario/inventario/urls.py
# urls.py del proyecto
from django.contrib import admin # Importa el administrador
from django.urls import path, include  # Importa las URLs
from django.views.generic import RedirectView # Importa la vista RedirectView
from gestion_inventario import views # Importa la vista

urlpatterns = [
    path('', RedirectView.as_view(url='login/', permanent=False), name='index'), # Redirecciona a la página de inicio desde un principio
    path('admin/', admin.site.urls), # URL del administrador
    path('login/', views.LoginList.as_view(), name='login'),  # Página de inicio de sesión
    path('logout/', views.LogoutList.as_view(), name='logout'), # Página de inicio de sesión como la página principal
    path('registro/', views.RegistroList.as_view(), name='registro'), # Página de registro
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'), # Página de inicio
    path('gestion_inventario/', include('gestion_inventario.urls')), # URL de la app gestion_inventario
    path('accounts/profile/', RedirectView.as_view(url='dashboard/', permanent=False)), # Redirecciona a la página de inicio al iniciar la sesión (dashboard)include('django.contrib.auth.urls')),
]

inventario/gestion_inventario/models.py
# models.py
from django.db import models # Importa el modelo de base de datos
from django.contrib.auth.models import User # Importa el modelo de usuario
# Create your models here.
class Proveedor(models.Model): # Define la clase Proveedor
    nombre = models.CharField(max_length=255) # Define el campo nombre como una cadena de caracteres
    contacto = models.CharField(max_length=255) # Define el campo contacto como una cadena de caracteres
    telefono = models.CharField(max_length=15) # Define el campo telefono como una cadena de caracteres
    direccion = models.TextField() # Define el campo direccion como un campo de texto
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='proveedores') # Define el campo user como una clave foránea
 
    def __str__(self): # Sobrescribe el método __str__ para mostrar el nombre del proveedor
        return self.nombre

class Producto(models.Model): # Define la clase Producto
    usuario = models.ForeignKey(User, on_delete=models.CASCADE) # Define el campo usuario como una clave foránea
    nombre = models.CharField(max_length=255) # Define el campo nombre como una cadena de caracteres
    descripcion = models.TextField() # Define el campo descripcion como un campo de texto
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE) # Define el campo proveedor como una clave foránea
    precio = models.DecimalField(max_digits=10, decimal_places=2) # Define el campo precio como un decimal
    stock = models.IntegerField() # Define el campo stock como un entero

    def __str__(self): # Sobrescribe el método __str__ para mostrar el nombre del producto
        return self.nombre
    
    def actualizar_stock(self, cantidad, operacion): # Define el método actualizar_stock
        if operacion == 'Compra': 
            self.stock += cantidad
        elif operacion == 'Venta':
            self.stock -= cantidad
        self.save()

class Pedido(models.Model): # Define la clase Pedido
    TIPO_PEDIDO = (
        ('Compra', 'Compra'),
        ('Venta', 'Venta'),
    )
    tipo = models.CharField(max_length=6, choices=TIPO_PEDIDO) # Define el campo tipo como una cadena de caracteres
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE) # Define el campo proyecto como una clave foránea
    cantidad = models.IntegerField() # Define el campo cantidad como un entero
    fecha = models.DateTimeField(auto_now_add=True) # Define el campo fecha como una fecha

    def __str__(self): # Sobrescribe el método __str__ para mostrar el tipo de pedido
        return f"{self.tipo} - {self.producto.nombre} - {self.cantidad}"
    
    def save(self, *args, **kwargs): # Sobrescribe el método save
        """
        Sobrescribe el método save para actualizar el stock del producto.
        """
        super().save(*args, **kwargs)
        self.producto.actualizar_stock(self.cantidad, self.tipo) # Actualiza el stock del producto

inventario/gestion_inventario/views.py
# views.py en tu aplicación gestion_inventario
import matplotlib # Importa la librería matplotlib
matplotlib.use('Agg') # Establece el backend de matplotlib para 'Agg'
from .models import Proveedor, Producto, Pedido # Importa los modelos
from django.views.generic import FormView, CreateView, View, ListView, UpdateView, DeleteView, TemplateView # Importa las clases genericas
from django.urls import reverse_lazy # Importa la clase reverse_lazy
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm # Importa los formularios
from django.contrib.auth import login, logout # Importa las funciones login y logout
from django.shortcuts import redirect, render # Importa las funciones redirect y render
from django.contrib.auth.mixins import LoginRequiredMixin # Importa la clase LoginRequiredMixin
from .models import Proveedor, Pedido, Producto # Importa los modelos
from django.utils.dateparse import parse_datetime # Importa la clase parse_datetime
import matplotlib.pyplot as plt # Importa la librería matplotlib
import io # Importa la clase io
import urllib, base64 # Importa las clases urllib y base64
from django.http import HttpResponse # Importa la clase HttpResponse


class LoginRedirectView(View): # Clase que redirige al usuario dependiendo de si está autenticado o no
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('dashboard')  # Si el usuario está autenticado, redirige al dashboard
        else:
            return redirect('login')  # Si no está autenticado, redirige al inicio de sesión

class LoginList(FormView): # Clase que permite el inicio de sesión
    template_name = 'registration/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('dashboard')
    
    def form_valid(self, form):
        user = form.get_user()
        if user is not None:
            login(self.request, user)  # Autentica al usuario
            return super().form_valid(form)
        else:
            return self.form_invalid(form)
    
class RegistroList(CreateView): # Clase que permite el registro
    template_name = 'registro.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    
    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.save()
        login(self.request, user)  # Autenticar al usuario después del registro
        return response
    
class LogoutList(View): # Clase que permite el cierre de sesión
    def post(self, request, *args, **kwargs): 
        logout(request) # Cierra la sesión
        return redirect(reverse_lazy('login')) 
    
class DashboardView(LoginRequiredMixin, TemplateView): # Clase que muestra el dashboard
    template_name = 'dashboard.html'
    
    def get_context_data(self, **kwargs): # Obtiene los datos para el dashboard
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user.username # Obtiene el nombre de usuario
        return context

class ProveedorList(ListView, LoginRequiredMixin): # Clase que muestra la lista de proveedores
    model = Proveedor
    template_name = 'lista_proveedores.html'
    context_object_name = 'proveedores'
    
    def get_queryset(self): # Obtiene los datos de la lista de tareas
        return Proveedor.objects.filter(user=self.request.user)
    
    def get_context_data(self, **kwargs): # Obtiene los datos para el dashboard
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user.username
        return context
    
class ProveedorCreate(CreateView, LoginRequiredMixin): # Clase que permite crear un nuevo proveedor
    model = Proveedor
    fields = ['nombre', 'telefono', 'direccion']
    template_name = 'nuevo_proveedor.html'
    success_url = reverse_lazy('dashboard')
    
    
    def form_valid(self, form): # Verifica que el formulario sea valido
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class ProveedorUpdate(UpdateView, LoginRequiredMixin): # Clase que permite editar un proveedor
    model = Proveedor 
    fields = ['nombre', 'telefono', 'direccion']
    template_name = 'nuevo_proveedor.html'
    success_url = reverse_lazy('proveedor-list')
    
class ProveedorDelete(DeleteView, LoginRequiredMixin): # Clase que permite eliminar un proveedor
    model = Proveedor
    success_url = reverse_lazy('proveedor-list')
    template_name = 'borrar_proveedor.html'

class ProductoList(ListView, LoginRequiredMixin): # Clase que muestra la lista de productos
    model = Producto
    template_name = 'lista_productos.html'
    context_object_name = 'productos'
    
    def get_queryset(self): # Obtiene los datos de la lista de tareas
        return Producto.objects.filter(usuario=self.request.user)
    
    def get_context_data(self, **kwargs): # Obtiene los datos para el dashboard
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user.username
        return context
    
    
class ProductoCreate(CreateView, LoginRequiredMixin): # Clase que permite crear un nuevo producto
    model = Producto
    fields = ['nombre', 'descripcion', 'proveedor', 'stock', 'precio']
    template_name = 'nuevo_producto.html'
    success_url = reverse_lazy('producto-list')
    
    def form_valid(self, form): # Verifica que el formulario sea valido
        form.instance.usuario = self.request.user
        return super().form_valid(form)
    
class ProductoUpdate(UpdateView, LoginRequiredMixin): # Clase que permite editar un producto
    model = Producto
    fields = ['nombre', 'descripcion', 'proveedor', 'stock', 'precio']
    template_name = 'nuevo_producto.html'
    success_url = reverse_lazy('producto-list')
    
    
class ProductoDelete(DeleteView, LoginRequiredMixin): # Clase que permite eliminar un producto
    model = Producto
    success_url = reverse_lazy('producto-list')
    template_name = 'borrar_producto.html'


class PedidoList(ListView, LoginRequiredMixin): # Clase que muestra la lista de pedidos
    model = Pedido
    template_name = 'lista_pedidos.html'
    context_object_name = 'pedidos'
    
    def get_queryset(self): # Obtiene los datos de la lista de tareas
        return Pedido.objects.filter(producto__usuario=self.request.user)
    
    def get_context_data(self, **kwargs): # Obtiene los datos para el dashboard
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user.username
        return context
    
class PedidoCreate(CreateView, LoginRequiredMixin): # Clase que permite crear un nuevo pedido
    model = Pedido
    fields = ['tipo', 'producto', 'cantidad']
    template_name = 'nuevo_pedido.html'
    success_url = reverse_lazy('pedido-list')
    
    def form_valid(self, form): # Verifica que el formulario sea valido
        response = super().form_valid(form)
        fecha_str = self.request.POST.get('fecha')
        if fecha_str:
            fecha = parse_datetime(fecha_str)
            if fecha:
                self.object.fecha = fecha
                self.object.save()
        return response
    
class PedidoUpdate(UpdateView, LoginRequiredMixin): # Clase que permite editar un pedido
    model = Pedido
    fields = ['tipo', 'producto', 'cantidad', ]
    template_name = 'nuevo_pedido.html'
    success_url = reverse_lazy('pedido-list')
    
    def form_valid(self, form): # Verifica que el formulario sea valido
        response = super().form_valid(form)
        fecha_str = self.request.POST.get('fecha')
        if fecha_str:
            fecha = parse_datetime(fecha_str)
            if fecha:
                self.object.fecha = fecha
                self.object.save()
        return response
    
class PedidoDelete(DeleteView, LoginRequiredMixin): # Clase que permite eliminar un pedido
    model = Pedido
    success_url = reverse_lazy('pedido-list')
    template_name = 'borrar_pedido.html'


def lista_productos(request): # Muestra la lista de productos
    productos = Producto.objects.filter(usuario=request.user)
    return render(request, 'lista_productos.html', {'productos': productos})

def informe_stock(request): # Muestra el informe de stock
    # Filtrar los productos basados en el usuario actual
    productos_usuario = Producto.objects.filter(usuario=request.user)
    
    context = {
        'productos': productos_usuario,
        'username': request.user.username
    }
    return render(request, 'informes_stock.html', context)


def grafico_stock(request): # Muestra el gráfico de stock
    productos_usuario = Producto.objects.filter(usuario=request.user)

    # Datos para el gráfico
    nombres_productos = [producto.nombre for producto in productos_usuario]
    cantidades_stock = [producto.stock for producto in productos_usuario]
    plt.fill_between( nombres_productos, cantidades_stock, alpha=0.1, color='blue')

   # Crear el gráfico
    plt.figure(figsize=(7, 5))
    plt.plot(nombres_productos, cantidades_stock, marker='o', linewidth=2)
    plt.title('Gráfico de Stock')
    plt.xlabel('Productos')
    plt.ylabel('Stock')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.grid(True)
    

# Guardar el gráfico en un objeto BytesIO
    buffer = io.BytesIO()
    plt.savefig(buffer, format='png')
    plt.close()
    buffer.seek(0)
    image_png = buffer.getvalue()
    buffer.close()

# Convertir a base64 para incrustar en HTML
    graphic = base64.b64encode(image_png)
    graphic = graphic.decode('utf-8')

    context = {
   'graphic': graphic
   }
    return render(request, 'grafico_stock.html', context)

def descargar_grafico_stock(request): # Descarga el gráfico de stock
    productos_usuario = Producto.objects.filter(usuario=request.user)

    # Datos para el gráfico
    nombres_productos = [producto.nombre for producto in productos_usuario]
    cantidades_stock = [producto.stock for producto in productos_usuario]

inventario/gestion_inventario/templates/borrar_pedido.html
<!--borrar_pedido.html-->
{% load static %} <!-- Cargar el archivo static -->
<!DOCTYPE html>
<html lang="es"> <!-- Idioma de la página -->
<head>
    <meta charset="UTF-8"> <!-- Codificación de caracteres -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- Escala de la página -->
    <title>Borrar Pedido</title> <!-- Título de la página -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/borrar_pedido.css' %}"> <!-- Enlazar el archivo CSS -->
</head>
<body>
    <div class="borrar-pedido"> <!-- Contenedor de la página -->
        <h2>¿Estás seguro de que deseas eliminar este pedido?</h2> <!-- Título de la página -->
        <form method="post"> <!-- Formulario para enviar los datos --> 
            {% csrf_token %} <!-- Token de seguridad -->
            <input type="submit" value="Sí, borrar"> <!-- Botón para enviar los datos -->
        </form>
        <a href="{% url 'pedido-list' %}" class="cancelar">Cancelar</a> <!-- Botón para cancelar la operación -->
    </div>
</body>
</html>

inventario/gestion_inventario/templates/borrar_producto.html
<!--borrar_producto.html-->
{% load static %} <!-- Cargar el archivo static, Javascript, etc. -->
<!DOCTYPE html>
<html lang="es"> <!-- Idioma de la página -->
<head>
    <meta charset="UTF-8"> <!-- Codificación de caracteres -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- Escala de la página -->
    <title>Borrar Producto</title> <!-- Título de la página -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/borrar_producto.css' %}"> <!-- Cargar el archivo CSS -->
</head>
<body>
    <div class="borrar-producto"> <!-- Div para centrar el contenido -->
        <h2>¿Estás seguro de que deseas eliminar este producto?</h2> <!-- Título de la página -->
        <form method="post"> <!-- Formulario para enviar los datos -->
            {% csrf_token %} <!-- Token de seguridad -->
            <input type="submit" value="Sí, borrar"> <!-- Botón para borrar el producto -->
        </form>
        <a href="{% url 'producto-list' %}" class="cancelar">Cancelar</a> <!-- Botón para cancelar la eliminación -->
    </div>
</body>
</html>

inventario/gestion_inventario/templates/borrar_proveedor.html
<!--borrar_proveedor.html-->
{% load static %} <!-- Carga el archivo static -->
<!DOCTYPE html>
<html lang="es"> <!-- Idioma de la página -->
<head>
    <meta charset="UTF-8"> <!-- Codificación de caracteres -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- Escala de la página -->
    <title>Borrar Proveedor</title> <!-- Título de la página -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/borrar_proveedor.css' %}"> <!-- Carga el archivo CSS -->
</head>
<body>
    <div class="borrar-proveedor"> <!-- Contenedor principal -->
        <h2>¿Estás seguro de que deseas eliminar este proveedor?</h2> <!-- Título de la página -->
        <form method="post"> <!-- Formulario para enviar los datos -->
            {% csrf_token %} <!-- Token de seguridad -->
            <input type="submit" value="Sí, borrar"> <!-- Botón para borrar el proveedor -->
        </form>
        <a href="{% url 'proveedor-list' %}" class="cancelar">Cancelar</a> <!-- Botón para cancelar la operación -->
    </div>
</body>
</html>

inventario/gestion_inventario/templates/crear_pedido.html
<!--crear_pedido.html-->
<!DOCTYPE html>
<html lang="es"> <!-- Lenguaje de la página -->
<head>
    <meta charset="UTF-8"> <!-- Codificación de caracteres -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- Tamaño de la ventana -->
    <title>Crear Pedido</title> <!-- Título de la página -->
</head>
<body>
    <h2>Crear Pedido</h2> <!-- Título de la página -->
    <form method="post"> <!-- Formulario para enviar los datos -->
        {% csrf_token %} <!-- Token CSRF -->
        <label for="tipo">Tipo de Pedido:</label><br> <!-- Etiqueta para el campo de tipo de pedido -->
        <select id="tipo" name="tipo"> <!-- Campo de tipo de pedido -->
            <option value="Compra">Compra</option> <!-- Opción para el campo de tipo de pedido, comprar -->
            <option value="Venta">Venta</option> <!-- Opción para el campo de tipo de pedido, vender -->
        </select><br>
        <label for="producto">Producto:</label><br> <!-- Etiqueta para el campo de producto -->
        <select id="producto" name="producto"> <!-- Campo de producto -->
            {% for producto in productos %} <!-- Ciclo para mostrar los productos -->
            <option value="{{ producto.id }}">{{ producto.nombre }}</option> <!-- Opción para el campo de producto -->
            {% endfor %} <!-- Fin del ciclo -->
        </select><br>
        <label for="cantidad">Cantidad:</label><br> <!-- Etiqueta para el campo de cantidad -->
        <input type="number" id="cantidad" name="cantidad"><br><br> <!-- Campo de cantidad -->
        <input type="submit" value="Crear Pedido"> <!-- Botón para enviar los datos -->
    </form>
</body>
</html>

inventario/gestion_inventario/templates/dashboard.html
<!-- dashboard.html -->
{% load static %} <!-- Cargar archivos estáticos -->
<!DOCTYPE html>
<html lang="es"> <!-- Idioma -->
<head>
    <meta charset="UTF-8"> <!-- Codificación de caracteres -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- Escala de visualización -->
    <title>Dashboard</title> <!-- Título de la página -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}"> <!-- Enlazar archivo CSS -->
</head>
<body>
    <div class="dashboard-container"> <!-- Contenedor -->
        <div class="panel"> <!-- Panel -->
            <h2>¡Bienvenido, {{ username }}!</h2> <!-- Título -->
            <ul class="dashboard-menu"> <!-- Lista de opciones -->
                <li><a href="{% url 'proveedor-list' %}">Proveedores</a></li> <!-- Enlace a lista de proveedores -->
                <li><a href="{% url 'producto-list' %}">Productos</a></li> <!-- Enlace a lista de productos -->
                <li><a href="{% url 'pedido-list' %}">Pedidos</a></li> <!-- Enlace a lista de pedidos -->
                <li><a href="{% url 'informe-stock' %}">Informe de Stock</a></li> <!-- Enlace a informe de stock -->
                <li>
                   <form method="post" action="{% url 'logout' %}"> <!-- Formulario para cerrar sesión -->
                       {% csrf_token %} <!-- Token CSRF -->
                       <button type="submit" class="logout-button">Cerrar Sesión</button> <!-- Botón para cerrar sesión -->
                   </form>
               </li>
           </ul>
       </div>
       <div class="proveedores-content"> <!-- Contenido -->
           {% block content %}{% endblock %} <!-- Bloque de contenido -->
       </div>
    </div>
</body>
</html>

inventario/gestion_inventario/templates/grafico_stock.html
<!-- templates/grafico_stock.html -->
{% load static %} <!-- Cargar archivos estáticos como CSS, Javascript, etc. -->
<!DOCTYPE html>
<html lang="es"> <!-- Idioma de la página -->
<head>
    <meta charset="UTF-8"> <!-- Codificación de caracteres -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- Escala de la página -->
    <title>Gráfico de Stock</title> <!-- Título de la página -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/grafico_stock.css' %}"> <!-- Enlazar archivo CSS -->
</head>
<body>
    <div class="container"> <!-- Contenedor de la página -->
        <h2>Gráfico de Stock</h2> <!-- Título de la página -->
        <img src="data:image/png;base64,{{ graphic }}" alt="Gráfico de Stock"> <!-- Imagen del gráfico -->
        <br><br>
        <button class="boton-volver-stock" onclick="window.location.href='{% url 'informe-stock' %}'">Volver al Informe de Stock</button> <!-- Botón para volver al informe de stock -->
        <button class="boton-descargar-stock" onclick="window.location.href='{% url 'descargar_grafico_stock' %}'">Descargar Gráfico</button> <!-- Botón para descargar el gráfico -->
    </div>
</body>
</html>

inventario/gestion_inventario/templates/informes_stock.html
<!--informes_stock.html-->
{% extends 'dashboard.html' %} <!-- Extender la plantilla de dashboard -->

{% block content %} <!-- Contenido de la plantilla -->
<h2>Informe de Stock</h2> <!-- Título -->
<table>
    <thead>
        <tr>
            <th>Producto</th> <!-- Encabezado de la tabla -->
            <th>Stock</th> <!-- Encabezado de la tabla -->
        </tr>
    </thead>
    <tbody>
        {% for producto in productos %} <!-- Ciclo para mostrar los productos -->
        <tr>
            <td>{{ producto.nombre }}</td> <!-- Celda para mostrar el nombre del producto -->
            <td>{{ producto.stock }}</td> <!-- Celda para mostrar el stock del producto -->
        </tr>
            {% endfor %} <!-- Fin del ciclo -->
        </tbody>
</table>
<button class="boton-grafico-stock" onclick="window.location.href='{% url 'grafico_stock' %}'">Ver Gráfico de Stock</button> <!-- Botón para mostrar el gráfico de stock -->
{% endblock %} <!-- Fin del contenido de la plantilla -->

inventario/gestion_inventario/templates/nuevo_pedido.html
<!--nuevo_pedido.html-->
{% load static %} <!-- Carga el directorio 'static' -->
<!DOCTYPE html>
<html lang="es"> <!-- Idioma de la página -->
<head>
    <meta charset="UTF-8"> <!-- Codificación de caracteres -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> <!-- Escala de la página -->
    <title>Nuevo Pedido</title> <!-- Título de la página -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/nuevo_pedido.css' %}"> <!-- Enlaza el archivo CSS -->
</head>
<body>
    <div class="nuevo-pedido"> <!-- Contenedor de la página -->
        <h2>Nuevo Pedido</h2> <!-- Título de la página -->
        <form method="post"> <!-- Formulario para enviar los datos -->
            {% csrf_token %} <!-- Token CSRF -->
            {{ form.as_p }} <!-- Envía los datos del formulario -->
            <label for="id_fecha">Fecha</label> <!-- Etiqueta para el campo 'fecha' -->
            <input type="datetime-local" id="id_fecha" name="fecha" value="{{ pedido.fecha|date:'Y-m-d\\TH:i' }}"> <!-- Campo 'fecha' -->
            <input type="submit" value="Guardar"> <!-- Botón 'Guardar' -->
        </form>
    </div>
</body>
</html>